In [1]:
# Importing necessary libraries

import tensorflow as tf
import numpy as np
import random

In [2]:
# Assume each dance move to be a label numbered from 0-9.

random.seed(100)

dance_move_num=[]
for i in range(10000):
    dance_move_num.append(random.randint(0,9))
dance_move_num=np.array(dance_move_num)

# Assume each second in the music is represented by 2 values- Beat, and frequency.
# Let all values of music be within the range of 0-100.

music=[]
for i in range(10000):         # Giving a definitive pattern to the music values and dance
    if(dance_move_num[i]==0):
        music.append([random.randrange(0,10),random.randrange(90,101)])
    elif(dance_move_num[i]==1):
        music.append([random.randrange(10,20),random.randrange(80,90)])
    elif(dance_move_num[i]==2):
        music.append([random.randrange(20,30),random.randrange(70,80)])
    elif(dance_move_num[i]==3):
        music.append([random.randrange(30,40),random.randrange(60,70)])
    elif(dance_move_num[i]==4):
        music.append([random.randrange(40,50),random.randrange(50,60)])
    elif(dance_move_num[i]==5):
        music.append([random.randrange(50,60),random.randrange(40,50)])
    elif(dance_move_num[i]==6):
        music.append([random.randrange(60,70),random.randrange(30,40)])
    elif(dance_move_num[i]==7):
        music.append([random.randrange(70,80),random.randrange(20,30)])
    elif(dance_move_num[i]==8):
        music.append([random.randrange(80,90),random.randrange(10,20)])
    elif(dance_move_num[i]==9):
        music.append([random.randrange(90,101),random.randrange(0,10)])
music=np.array(music)

In [3]:
dance_move_num

array([2, 7, 7, ..., 1, 8, 0])

In [4]:
music

array([[29, 72],
       [75, 23],
       [72, 23],
       ...,
       [17, 81],
       [83, 15],
       [ 6, 98]])

In [5]:
# Split into train and test data in a 70:30 ratio respectively

training_dance_move_num=dance_move_num[0:7000]
training_music=music[0:7000]
test_dance_move_num=dance_move_num[7000:]
test_music=music[7000:]

In [6]:
training_music

array([[29, 72],
       [75, 23],
       [72, 23],
       ...,
       [84, 14],
       [16, 89],
       [35, 64]])

In [7]:
training_dance_move_num

array([2, 7, 7, ..., 8, 1, 3])

In [8]:
# Using DNN neural networks because of using a very small number of dance moves.
# Small number of dance moves is chosen because of this being a prototype.
# LSTM neural network will be used when building the real model with real-time data.

# Consturction of the DNN neural network.

model=tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(32, activation=tf.keras.activations.relu))
model.add(tf.keras.layers.Dense(16, activation=tf.keras.activations.relu))
model.add(tf.keras.layers.Dense(10, activation=tf.keras.activations.softmax))

In [9]:
# defining optimizer, loss, and metrics for the model.

model.compile(optimizer=tf.keras.optimizers.Adam(),loss=tf.keras.losses.sparse_categorical_crossentropy,metrics=["accuracy"])

In [10]:
# training model

model.fit(training_music,training_dance_move_num,epochs=10)

Epoch 1/10


2024-02-03 23:26:57.209612: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


219/219 [==============================] - 0s 515us/step - loss: 1.9880 - accuracy: 0.5589
Epoch 2/10
219/219 [==============================] - 0s 526us/step - loss: 0.3708 - accuracy: 0.9609
Epoch 3/10
219/219 [==============================] - 0s 490us/step - loss: 0.1782 - accuracy: 0.9907
Epoch 4/10
219/219 [==============================] - 0s 486us/step - loss: 0.1140 - accuracy: 0.9956
Epoch 5/10
219/219 [==============================] - 0s 478us/step - loss: 0.0838 - accuracy: 0.9969
Epoch 6/10
219/219 [==============================] - 0s 479us/step - loss: 0.0639 - accuracy: 0.9984
Epoch 7/10
219/219 [==============================] - 0s 648us/step - loss: 0.0531 - accuracy: 0.9976
Epoch 8/10
219/219 [==============================] - 0s 491us/step - loss: 0.0459 - accuracy: 0.9964
Epoch 9/10
219/219 [==============================] - 0s 478us/step - loss: 0.0390 - accuracy: 0.9977
Epoch 10/10
219/219 [==============================] - 0s 475us/step - loss: 0.0340 - accurac

In [11]:
# Summary of model.

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 2)                 0         
                                                                 
 dense (Dense)               (None, 32)                96        
                                                                 
 dense_1 (Dense)             (None, 16)                528       
                                                                 
 dense_2 (Dense)             (None, 10)                170       
                                                                 
Total params: 794
Trainable params: 794
Non-trainable params: 0
_________________________________________________________________


In [12]:
# Observing results for unseen data. 
# As the accuracy for unseen data is also high, we can assume that the model works perfectly without overfitting.

model.evaluate(test_music,test_dance_move_num)

94/94 [==============================] - 0s 443us/step - loss: 0.0317 - accuracy: 0.9997


[0.031730685383081436, 0.999666690826416]

In [13]:
# Predicitng a random value.
# The output gives the probability of the dance moves in the order from 0 to 9.

a=model.predict([[93,3]])
print(a)

1/1 [==============================] - 0s 59ms/step
[[2.08436995e-06 4.39218365e-20 2.74330959e-13 5.72716880e-15
  1.21173425e-14 4.22548146e-14 3.26560380e-18 3.66471176e-14
  1.59053870e-05 9.99982119e-01]]


In [14]:
# The output returns the dance move number with highest probabilty.

np.argmax(a)

9

In [15]:
# Continuous dance steps for a song lasting 30 sec.

dance_moves=[]
for i in range(30):
    z=model.predict(np.array([test_music[i]]))
    dance_moves.append(np.argmax(z))

1/1 [==============================] - 0s 12ms/step


In [16]:
# Dance moves

dance_moves=np.array(dance_moves)
dance_moves

array([4, 1, 5, 5, 6, 8, 4, 9, 9, 4, 6, 6, 4, 1, 5, 5, 3, 5, 8, 8, 6, 6,
       3, 0, 2, 7, 6, 4, 1, 7])